// <auto-generated />
using BookStore.MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore.MSSQL.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookStore.MSSQL.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Толстой",
                            Date = "2022-08-10",
                            Title = "Война и мир"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Достоевский",
                            Date = "2022-08-09",
                            Title = "Преступление и наказание"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Булгаков",
                            Date = "2022-08-08",
                            Title = "Мастер и Маргарита"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Грибоедов",
                            Date = "2022-08-07",
                            Title = "Горе от ума"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Горький",
                            Date = "2022-08-06",
                            Title = "На дне"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Толстой",
                            Date = "2022-08-06",
                            Title = "Детство"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Булгаков",
                            Date = "2022-08-06",
                            Title = "Мастер и Маргарита"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
